# Generated by Django 2.1.3 on 2018-12-04 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='Nombre')),
                ('album', models.CharField(blank=True, max_length=255, null=True, verbose_name='Álbum')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('youtube_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Url de YouTube')),
                ('enabled', models.BooleanField(default=False, verbose_name='Habilitado')),
                ('cover', models.FileField(blank=True, null=True, upload_to='', verbose_name='Caratula')),
                ('song', models.FileField(upload_to='', verbose_name='Canción')),
                ('likes_amount', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad de me gusta')),
            ],
            options={
                'verbose_name': 'Podcast',
                'verbose_name_plural': 'Podcasts',
            },
        ),
        migrations.AddField(
            model_name='like',
            name='podcast',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='podcasts.Podcast'),
        ),
    ]
