# Generated by Django 2.1.3 on 2018-12-04 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podcasts', '0004_podcast_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='podcast',
            name='year',
            field=models.IntegerField(default=2018),
        ),
    ]
